# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: Docker Test App

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:3.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: root
          - POSTGRES_PASSWORD: password
          - POSTGRES_DB: docker-test-app
          - POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: RAILS_ENV=test bundle exec gem install rake
      - run: bundle install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load

      # Specs
      - run:
          name: Run tests
          command: bundle exec rails test
